version: "3.3"

services:
  myapp-server:
    build:
      dockerfile: Dockerfile
      context: ../
    restart: always
    environment:
      - SERVER_ALLOWED_ORIGINS=['http://localhost:3000']
      - LOG_LEVEL_HTTP=0
      - OIDC_SERVER=http://127.0.0.1:8090/auth/realms/evote
      - KEYCLOAK_CONTAINER=keycloak_keycloak_1
    ports:
      - "8080:8080"
    networks:
      - keycloak_default

networks:
  keycloak_default:
    external: true